# Template Decision Tree Using Breast Cancer Data

## Importing The Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing The Dataset

In [6]:
# Importing Dataset
dataset = pd.read_csv('Human Stress.csv')
X = np.array(dataset.iloc[:,1:-1])
y = np.array(dataset.iloc[:,-1])

In [3]:
dataset

ID      sr      rr       t      lm      bo     rem   sr.1     hr  sl
0      1  93.800  25.680  91.840  16.600  89.840   99.60  1.840  74.20   3
1      2  91.640  25.104  91.552  15.880  89.552   98.88  1.552  72.76   3
2      3  60.000  20.000  96.000  10.000  95.000   85.00  7.000  60.00   1
3      4  85.760  23.536  90.768  13.920  88.768   96.92  0.768  68.84   3
4      5  48.120  17.248  97.872   6.496  96.248   72.48  8.248  53.12   0
..   ...     ...     ...     ...     ...     ...     ...    ...    ...  ..
625  626  69.600  20.960  92.960  10.960  90.960   89.80  3.440  62.40   2
626  627  48.440  17.376  98.064   6.752  96.376   73.76  8.376  53.44   0
627  628  97.504  27.504  86.880  17.752  84.256  101.88  0.000  78.76   4
628  629  58.640  19.728  95.728   9.728  94.592   84.32  6.728  59.32   1
629  630  73.920  21.392  93.392  11.392  91.392   91.96  4.088  63.48   2

[630 rows x 10 columns]

In [7]:
X

array([[ 93.8  ,  25.68 ,  91.84 , ...,  99.6  ,   1.84 ,  74.2  ],
       [ 91.64 ,  25.104,  91.552, ...,  98.88 ,   1.552,  72.76 ],
       [ 60.   ,  20.   ,  96.   , ...,  85.   ,   7.   ,  60.   ],
       ...,
       [ 97.504,  27.504,  86.88 , ..., 101.88 ,   0.   ,  78.76 ],
       [ 58.64 ,  19.728,  95.728, ...,  84.32 ,   6.728,  59.32 ],
       [ 73.92 ,  21.392,  93.392, ...,  91.96 ,   4.088,  63.48 ]])

In [8]:
y

array([3, 3, 1, 3, 0, 1, 0, 0, 0, 1, 2, 1, 0, 4, 3, 1, 1, 3, 3, 2, 2, 2,
       2, 3, 3, 1, 2, 1, 3, 2, 0, 4, 0, 4, 2, 3, 0, 4, 0, 4, 2, 2, 2, 0,
       2, 4, 2, 4, 1, 4, 0, 1, 3, 0, 1, 2, 4, 3, 3, 1, 4, 3, 0, 2, 4, 1,
       0, 2, 4, 0, 1, 4, 1, 0, 0, 4, 4, 1, 3, 4, 1, 1, 1, 4, 2, 1, 1, 1,
       3, 4, 2, 3, 2, 4, 0, 2, 4, 2, 2, 3, 4, 4, 0, 4, 1, 2, 2, 2, 4, 1,
       2, 4, 0, 3, 2, 4, 2, 2, 0, 1, 1, 3, 4, 1, 3, 4, 4, 2, 1, 4, 2, 0,
       4, 3, 1, 0, 0, 2, 4, 0, 2, 3, 2, 0, 2, 0, 0, 0, 0, 1, 3, 0, 4, 4,
       0, 2, 3, 2, 4, 4, 4, 2, 1, 2, 4, 2, 0, 0, 4, 4, 1, 2, 2, 1, 1, 1,
       1, 4, 3, 1, 1, 1, 2, 1, 0, 2, 0, 2, 1, 2, 1, 1, 4, 3, 4, 0, 0, 0,
       2, 3, 0, 0, 0, 2, 4, 0, 2, 4, 1, 1, 1, 3, 0, 0, 3, 3, 0, 2, 2, 2,
       1, 4, 0, 1, 3, 4, 2, 1, 4, 0, 3, 4, 1, 3, 0, 0, 3, 4, 3, 1, 4, 3,
       3, 4, 3, 0, 3, 2, 3, 3, 1, 4, 2, 3, 1, 3, 2, 3, 4, 2, 4, 3, 2, 0,
       0, 1, 2, 3, 2, 2, 4, 4, 1, 0, 4, 1, 2, 3, 4, 3, 3, 3, 0, 3, 0, 1,
       3, 3, 3, 2, 4, 0, 4, 0, 4, 0, 2, 1, 2, 1, 3,

## Splitting The Dataset Into TrainingSet and TestSet

In [9]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test =train_test_split(X,y,test_size=0.20 ,random_state=0)

In [10]:
print(X_test)
print(y_test)

[[57.92  19.584 95.584 ... 83.96   6.584 58.96 ]
 [52.88  18.576 94.576 ... 81.44   5.576 56.44 ]
 [71.04  21.104 93.104 ... 90.52   3.656 62.76 ]
 ...
 [79.84  21.984 93.984 ... 94.92   4.976 64.96 ]
 [91.4   25.04  91.52  ... 98.8    1.52  72.6  ]
 [92.24  25.264 91.632 ... 99.08   1.632 73.16 ]]
[1 1 2 3 0 2 3 4 3 2 0 0 0 0 1 3 4 3 4 1 4 4 3 4 4 3 1 1 1 3 4 1 4 3 2 2 0
 4 2 0 0 1 3 0 2 1 0 3 0 1 4 0 0 3 0 0 1 4 2 3 1 2 3 2 3 2 3 4 3 0 4 0 3 0
 4 4 2 4 3 4 1 4 0 3 0 4 4 1 4 4 0 3 2 3 4 4 1 2 3 1 2 2 2 4 1 0 3 4 1 0 0
 4 0 2 4 3 0 0 0 2 3 2 2 2 3 3]


In [11]:
print(X_train)
print(y_train)

[[ 99.712  29.712  89.64  ... 104.64    0.     84.28 ]
 [ 76.32   21.632  93.632 ...  93.16    4.448  64.08 ]
 [ 52.32   18.464  94.464 ...  81.16    5.464  56.16 ]
 ...
 [ 81.32   22.352  90.176 ...  95.44    0.176  65.88 ]
 [ 96.384  26.384  85.48  ... 100.48    0.     75.96 ]
 [ 51.44   18.288  94.288 ...  80.72    5.288  55.72 ]]
[4 2 1 0 2 1 2 4 4 4 2 1 2 4 0 0 4 0 1 3 0 3 0 1 2 0 0 4 2 1 2 4 2 4 3 4 1
 1 1 4 3 3 2 2 2 1 1 1 2 4 3 3 3 4 4 0 3 4 0 1 3 3 2 4 1 1 1 0 2 2 2 3 3 1
 0 2 1 2 1 1 0 4 2 2 3 0 3 2 4 2 4 3 3 4 1 1 2 4 1 0 2 2 4 3 4 2 0 4 1 1 0
 2 4 4 2 1 0 4 3 4 4 1 0 1 3 3 4 4 2 0 0 0 4 4 2 4 1 0 4 1 0 0 4 4 0 2 2 0
 3 1 3 0 0 0 2 2 0 3 2 3 0 1 2 0 4 4 1 2 4 4 2 0 0 0 3 4 3 1 1 3 1 0 3 3 2
 2 0 4 0 3 1 1 1 1 0 1 1 3 4 4 1 3 0 1 0 0 1 2 3 0 4 2 0 2 2 1 2 2 0 1 4 3
 2 1 3 3 2 0 3 4 3 3 2 2 3 2 4 0 1 0 4 1 0 2 3 0 0 2 3 4 4 2 1 3 2 4 1 2 0
 3 3 0 4 0 1 1 2 2 4 4 2 3 1 3 4 3 4 2 3 0 3 3 3 4 1 0 0 4 2 0 2 3 1 0 1 0
 3 1 2 3 3 0 0 1 2 1 4 2 3 4 4 0 4 0 1 0 3 1 3 2 2 3 1 4 0 2 2 3

## Feature Scalling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
print(X_train)

[[ 1.48551275  2.03801977 -0.92164307 ...  1.38584487 -1.23770799
   2.03801977]
 [ 0.2670545  -0.02341509  0.22617086 ...  0.41003479  0.23466652
  -0.02341509]
 [-0.98307368 -0.83166083  0.46539461 ... -0.60997575  0.57098228
  -0.83166083]
 ...
 [ 0.52749787  0.16027713 -0.76752777 ...  0.60383679 -1.17944856
   0.16027713]
 [ 1.31216165  1.18895353 -2.1177618  ...  1.03224122 -1.23770799
   1.18895353]
 [-1.02891171 -0.87656337  0.41478959 ... -0.64737613  0.51272285
  -0.87656337]]


In [14]:
print(X_test)

[[-0.6913771  -0.54591739  0.78742658 ... -0.37197329  0.94172406
  -0.54591739]
 [-0.95390402 -0.80308649  0.49759781 ... -0.5861755   0.60805645
  -0.80308649]
 [-0.0079737  -0.15812271  0.07435579 ...  0.18563247 -0.02750089
  -0.15812271]
 ...
 [ 0.45040663  0.06638999  0.32738091 ...  0.55963634  0.40944479
   0.06638999]
 [ 1.0525517   0.8460614  -0.38108942 ...  0.88943974 -0.73455843
   0.8460614 ]
 [ 1.09630618  0.90321008 -0.34888622 ...  0.91323999 -0.69748425
   0.90321008]]


## Training Naive Bayes Model on the TrainSet

In [15]:
# Building Naive Bayes Model on our dataset
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Predicting a Single Result

In [16]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [2 2]
 [3 3]
 [0 0]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [3 3]
 [4 4]
 [4 4]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [4 4]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [3 3]
 [0 0]
 [1 1]
 [4 4]
 [0 0]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [4 4]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [0 0]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [0 0]
 [3 3]
 [1 2]
 [3 3]
 [4 4]
 [4 4]
 [1 1]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [1 1]
 [0 0]
 [3 3]
 [4 4]
 [1 1]
 [0 0]
 [0 0]
 [4 4]
 [0 0]
 [2 2]
 [4 4]
 [3 3]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [3 3]]


In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[28  0  0  0  0]
 [ 0 19  0  0  0]
 [ 0  1 21  0  0]
 [ 0  0  0 28  0]
 [ 0  0  0  0 29]]


In [18]:
accuracy_score(y_test,y_pred)

0.9920634920634921

## Model

In [32]:
input_data = float(input("Enter a value : "))
id_np_array = np.asarray(input_data)
id_reshaped = id_np_array.reshape(1,-1)
predict = classifier.predict(id_reshaped)
print(predict)

if(predict[0]==0):
    print("Low/Normal")
elif(predict[0]==1):
    print("Medium Low")
elif(predict[0]==2):
    print("Medium")
elif(predict[0]==3):
    print("Medium High")
else:
    print("High")

Enter a value : '93.8', '25.68', '91.84', '16.6', '89.84', '99.6', '1.84', '74.2'


ValueError: could not convert string to float: "'93.8', '25.68', '91.84', '16.6', '89.84', '99.6', '1.84', '74.2'"

In [34]:
input_data = 93.8, 25.68, 91.84, 16.6, 89.84, 99.6, 1.84, 74.2
id_np_array = np.asarray(input_data)
id_reshaped = id_np_array.reshape(1,-1)
predict = classifier.predict(id_reshaped)
#print(predict)

if(predict[0]==0):
    print("Low/Normal")
elif(predict[0]==1):
    print("Medium Low")
elif(predict[0]==2):
    print("Medium")
elif(predict[0]==3):
    print("Medium High")
else:
    print("High")

Medium


In [20]:
print(classifier.predict([[93.8, 25.68, 91.84, 16.6, 89.84, 99.6, 1.84, 74.2]]))

[2]


## Visualisasin Train Set

In [33]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('salmon', 'dodgerblue')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('salmon', 'dodgerblue'))(i), label = j)
plt.title('Decision Tree (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

ValueError: X has 2 features, but StandardScaler is expecting 8 features as input.

## Visualisasing Test Set

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('salmon', 'dodgerblue')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('salmon', 'dodgerblue'))(i), label = j)
plt.title('Decision Tree (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()