# Data Breast Cancer - **220523**


## ***Part 1 - Data Preparation***


### 1. Importing The Libraries

In [1]:
import numpy as np
import pandas as pd

### 2. Importing The Dataset

In [2]:
dataset = pd.read_csv('Human Stress.csv')

In [3]:
dataset

ID      sr      rr       t      lm      bo     rem   sr.1     hr  sl
0      1  93.800  25.680  91.840  16.600  89.840   99.60  1.840  74.20   3
1      2  91.640  25.104  91.552  15.880  89.552   98.88  1.552  72.76   3
2      3  60.000  20.000  96.000  10.000  95.000   85.00  7.000  60.00   1
3      4  85.760  23.536  90.768  13.920  88.768   96.92  0.768  68.84   3
4      5  48.120  17.248  97.872   6.496  96.248   72.48  8.248  53.12   0
..   ...     ...     ...     ...     ...     ...     ...    ...    ...  ..
625  626  69.600  20.960  92.960  10.960  90.960   89.80  3.440  62.40   2
626  627  48.440  17.376  98.064   6.752  96.376   73.76  8.376  53.44   0
627  628  97.504  27.504  86.880  17.752  84.256  101.88  0.000  78.76   4
628  629  58.640  19.728  95.728   9.728  94.592   84.32  6.728  59.32   1
629  630  73.920  21.392  93.392  11.392  91.392   91.96  4.088  63.48   2

[630 rows x 10 columns]

### 3. Checking The Missing data (Not Null)

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630 entries, 0 to 629
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ID      630 non-null    int64  
 1   sr      630 non-null    float64
 2   rr      630 non-null    float64
 3   t       630 non-null    float64
 4   lm      630 non-null    float64
 5   bo      630 non-null    float64
 6   rem     630 non-null    float64
 7   sr.1    630 non-null    float64
 8   hr      630 non-null    float64
 9   sl      630 non-null    int64  
dtypes: float64(8), int64(2)
memory usage: 49.3 KB


Maka dapat kita lihat dari hasil running syntax diatas bahwa tidak terdapat data kosong. Untuk cek lagi dapat menggunakan syntax dibawah ini

In [5]:
print(dataset.isnull().values.any())

False


In [6]:
dataset.isnull()

ID     sr     rr      t     lm     bo    rem   sr.1     hr     sl
0    False  False  False  False  False  False  False  False  False  False
1    False  False  False  False  False  False  False  False  False  False
2    False  False  False  False  False  False  False  False  False  False
3    False  False  False  False  False  False  False  False  False  False
4    False  False  False  False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
625  False  False  False  False  False  False  False  False  False  False
626  False  False  False  False  False  False  False  False  False  False
627  False  False  False  False  False  False  False  False  False  False
628  False  False  False  False  False  False  False  False  False  False
629  False  False  False  False  False  False  False  False  False  False

[630 rows x 10 columns]

### 4. Checking The Duplicated Data

In [7]:
# Memeriksa apakah benar adanya data yang terduplikasi atau tidak
print(dataset.duplicated().values.any())

False


In [8]:
# Menampilkan data yang ter-duplikasi
dataset.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
625    False
626    False
627    False
628    False
629    False
Length: 630, dtype: bool

In [9]:
# Menghitung berapa banyak data yang ter-duplikasi
print(dataset.duplicated().sum()) 
# Setelah dirunning di peroleh terdapat 3854 data yang mengalami duplikasi

0


### 4. Sclicing The New Dataset

In [10]:
X = np.array(dataset.iloc[:,:-1])
y = np.array(dataset.iloc[:,-1])
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630 entries, 0 to 629
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ID      630 non-null    int64  
 1   sr      630 non-null    float64
 2   rr      630 non-null    float64
 3   t       630 non-null    float64
 4   lm      630 non-null    float64
 5   bo      630 non-null    float64
 6   rem     630 non-null    float64
 7   sr.1    630 non-null    float64
 8   hr      630 non-null    float64
 9   sl      630 non-null    int64  
dtypes: float64(8), int64(2)
memory usage: 49.3 KB


### 5. Spliting The New dataset Into Training Set and Test Set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [12]:
print(X_train)
print(y_train)

[[5.8600e+02 7.4240e+01 2.1424e+01 ... 9.2120e+01 4.1360e+00 6.3560e+01]
 [1.9500e+02 9.8304e+01 2.8304e+01 ... 1.0288e+02 0.0000e+00 8.0760e+01]
 [1.7900e+02 9.2000e+01 2.5200e+01 ... 9.9000e+01 1.6000e+00 7.3000e+01]
 ...
 [3.6000e+02 8.1320e+01 2.2352e+01 ... 9.5440e+01 1.7600e-01 6.5880e+01]
 [1.9300e+02 9.6384e+01 2.6384e+01 ... 1.0048e+02 0.0000e+00 7.5960e+01]
 [5.6000e+02 5.1440e+01 1.8288e+01 ... 8.0720e+01 5.2880e+00 5.5720e+01]]
[2 4 3 4 1 1 1 4 3 3 2 2 2 1 1 1 2 4 3 3 3 4 4 0 3 4 0 1 3 3 2 4 1 1 1 0 2
 2 2 3 3 1 0 2 1 2 1 1 0 4 2 2 3 0 3 2 4 2 4 3 3 4 1 1 2 4 1 0 2 2 4 3 4 2
 0 4 1 1 0 2 4 4 2 1 0 4 3 4 4 1 0 1 3 3 4 4 2 0 0 0 4 4 2 4 1 0 4 1 0 0 4
 4 0 2 2 0 3 1 3 0 0 0 2 2 0 3 2 3 0 1 2 0 4 4 1 2 4 4 2 0 0 0 3 4 3 1 1 3
 1 0 3 3 2 2 0 4 0 3 1 1 1 1 0 1 1 3 4 4 1 3 0 1 0 0 1 2 3 0 4 2 0 2 2 1 2
 2 0 1 4 3 2 1 3 3 2 0 3 4 3 3 2 2 3 2 4 0 1 0 4 1 0 2 3 0 0 2 3 4 4 2 1 3
 2 4 1 2 0 3 3 0 4 0 1 1 2 2 4 4 2 3 1 3 4 3 4 2 3 0 3 3 3 4 1 0 0 4 2 0 2
 3 1 0 1 0 3 1 2 3 3 0 0 1 2 1 

In [13]:
print(X_test)
print(y_test)

[[392.     57.92   19.584 ...  83.96    6.584  58.96 ]
 [440.     52.88   18.576 ...  81.44    5.576  56.44 ]
 [312.     71.04   21.104 ...  90.52    3.656  62.76 ]
 ...
 [542.     54.48   18.896 ...  82.24    5.896  57.24 ]
 [ 98.     75.2    21.52  ...  92.6     4.28   63.8  ]
 [612.     98.592  28.592 ... 103.24    0.     81.48 ]]
[1 1 2 3 0 2 3 4 3 2 0 0 0 0 1 3 4 3 4 1 4 4 3 4 4 3 1 1 1 3 4 1 4 3 2 2 0
 4 2 0 0 1 3 0 2 1 0 3 0 1 4 0 0 3 0 0 1 4 2 3 1 2 3 2 3 2 3 4 3 0 4 0 3 0
 4 4 2 4 3 4 1 4 0 3 0 4 4 1 4 4 0 3 2 3 4 4 1 2 3 1 2 2 2 4 1 0 3 4 1 0 0
 4 0 2 4 3 0 0 0 2 3 2 2 2 3 3 4 2 1 0 2 1 2 4 4 4 2 1 2 4 0 0 4 0 1 3 0 3
 0 1 2 0 0 4 2 1 2 4]


### 6. Feature Scalling 

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
print(X_train)

[[ 1.47217245  0.15644453 -0.07546117 ...  0.32083852  0.14247605
  -0.07546117]
 [-0.66730601  1.4126299   1.69267533 ...  1.23739211 -1.23244288
   1.69267533]
 [-0.754855    1.08354943  0.89495793 ...  0.90688766 -0.70055935
   0.89495793]
 ...
 [ 0.23554295  0.52603364  0.16303166 ...  0.6036413  -1.17393569
   0.16303166]
 [-0.67824964  1.31240235  1.19924189 ...  1.03295637 -1.23244288
   1.19924189]
 [ 1.32990534 -1.03375771 -0.88140245 ... -0.65023128  0.52543219
  -0.88140245]]


In [16]:
print(X_test)

[[ 0.41064094 -0.6954897  -0.54833488 ... -0.37424302  0.95625785
  -0.54833488]
 [ 0.67328791 -0.95858704 -0.80738744 ... -0.58890056  0.62117123
  -0.80738744]
 [-0.02710402 -0.0106014  -0.15770007 ...  0.18454802 -0.01708901
  -0.15770007]
 ...
 [ 1.23141272 -0.87506407 -0.72514853 ... -0.52075531  0.72754793
  -0.72514853]
 [-1.19807177  0.20655831 -0.05078949 ...  0.36172566  0.19034557
  -0.05078949]
 [ 1.61443956  1.42766404  1.76669034 ...  1.26805747 -1.23244288
   1.76669034]]


## ***Part 3 - Logistic Regresion***

### 1. Training Logistic Regression Model on the TrainSet

In [17]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

### 2. Predicting A Single Result

In [18]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [2 2]
 [3 3]
 [0 0]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [3 3]
 [4 4]
 [4 4]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [4 4]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [3 3]
 [0 0]
 [1 1]
 [4 4]
 [0 0]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [4 4]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [0 0]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [0 0]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [4 4]
 [1 1]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [1 1]
 [0 0]
 [3 3]
 [4 4]
 [1 1]
 [0 0]
 [0 0]
 [4 4]
 [0 0]
 [2 2]
 [4 4]
 [3 3]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [3 3]
 [4 4]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [0 0]
 [0 0]
 [4 4]

### 3. Making The Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_logistic = confusion_matrix(y_test, y_pred)
print(cm_logistic)

[[36  0  0  0  0]
 [ 0 25  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 37]]


In [20]:
accuracy_score(y_test,y_pred)

1.0

## ***Part 4 - K-Nearest Neighbors***

### 1. Training KNN Model on The Train Set

In [21]:
# Building KNN Model on our dataset
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
classifier.fit(X_train, y_train)

KNeighborsClassifier()

### 2. Predicting a Single Result

In [22]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [2 2]
 [3 3]
 [0 0]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [3 3]
 [4 4]
 [4 4]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [4 4]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [3 3]
 [0 0]
 [1 1]
 [4 4]
 [0 0]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [4 4]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [0 0]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [0 0]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [4 4]
 [1 1]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [1 1]
 [0 0]
 [3 3]
 [4 4]
 [1 1]
 [0 0]
 [0 0]
 [4 4]
 [0 0]
 [2 2]
 [4 4]
 [3 3]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [3 3]
 [4 4]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [0 0]
 [0 0]
 [4 4]

### 3. Making The Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_knn = confusion_matrix(y_test, y_pred)
print(cm_knn)

[[36  0  0  0  0]
 [ 0 25  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 37]]


In [24]:
accuracy_score(y_test,y_pred)

1.0

## **Part 5 - Support Vector Machines**

### 1. Training SVM Model on The Train Set

In [25]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

### 2. Predicting a Single Result

In [26]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [2 2]
 [3 3]
 [0 0]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [3 3]
 [4 4]
 [4 4]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [4 4]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [3 3]
 [0 0]
 [1 1]
 [4 4]
 [0 0]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [4 4]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [0 0]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [0 0]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [4 4]
 [1 1]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [1 1]
 [0 0]
 [3 3]
 [4 4]
 [1 1]
 [0 0]
 [0 0]
 [4 4]
 [0 0]
 [2 2]
 [4 4]
 [3 3]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [3 3]
 [4 4]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [0 0]
 [0 0]
 [4 4]

### 3. Making The Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[36  0  0  0  0]
 [ 0 25  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 37]]


In [28]:
accuracy_score(y_test,y_pred)

1.0

## Part 7 - Kernel SVC

### 1. Training Kernel SVM Model on The Train Set

In [29]:
# Building SVM Model on our dataset
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

### 2. Predicting a Single Result

In [30]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [2 2]
 [3 3]
 [0 0]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [3 3]
 [4 4]
 [4 4]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [4 4]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [3 3]
 [0 0]
 [1 1]
 [4 4]
 [0 0]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [4 4]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [0 0]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [0 0]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [4 4]
 [1 1]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [1 1]
 [0 0]
 [3 3]
 [4 4]
 [1 1]
 [0 0]
 [0 0]
 [4 4]
 [0 0]
 [2 2]
 [4 4]
 [3 3]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [3 3]
 [4 4]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [0 0]
 [0 0]
 [4 4]

### 3. Making The Confusion Matrix

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[36  0  0  0  0]
 [ 0 25  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 37]]


In [32]:
#Akurasi score
accuracy_score(y_test,y_pred)

1.0

## Part 8 - Naive Bayes

### 1. Training Naive Bayes Model on Training Set

In [33]:
# Building Naive Bayes Model on our dataset
from sklearn.naive_bayes import GaussianNB
gnb_bayes = GaussianNB()
gnb_bayes.fit(X_train, y_train)

GaussianNB()

### 2. Predicting a Single Result

In [34]:
y_pred = gnb_bayes.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [2 2]
 [3 3]
 [0 0]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [3 3]
 [4 4]
 [4 4]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [4 4]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [3 3]
 [0 0]
 [1 1]
 [4 4]
 [0 0]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [4 4]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [0 0]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [0 0]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [4 4]
 [1 1]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [1 1]
 [0 0]
 [3 3]
 [4 4]
 [1 1]
 [0 0]
 [0 0]
 [4 4]
 [0 0]
 [2 2]
 [4 4]
 [3 3]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [3 3]
 [4 4]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [0 0]
 [0 0]
 [4 4]

### 3. Making The Confusion Matrix

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[36  0  0  0  0]
 [ 0 25  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 37]]


In [36]:
accuracy_score(y_test,y_pred)

1.0

## Part 9 - Decision Tree

### 1. Training Decision Tree Model on Training Set

In [37]:
# Building Naive Bayes Model on our dataset
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

### 2. Predicting a SIngle Result

In [38]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [2 2]
 [3 3]
 [0 0]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [3 3]
 [4 4]
 [4 4]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [4 4]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [3 3]
 [0 0]
 [1 1]
 [4 4]
 [0 0]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [4 4]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [0 0]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [0 0]
 [3 3]
 [1 2]
 [3 3]
 [4 4]
 [4 4]
 [1 1]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [1 1]
 [0 0]
 [3 3]
 [4 4]
 [1 1]
 [0 0]
 [0 0]
 [4 4]
 [0 0]
 [2 2]
 [4 4]
 [3 3]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [3 3]
 [4 4]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [0 0]
 [0 0]
 [4 4]

### 3. Making The Confusion Matrix

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[36  0  0  0  0]
 [ 0 25  0  0  0]
 [ 0  1 29  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 37]]


In [40]:
accuracy_score(y_test,y_pred)

0.9936708860759493

## Part 10 - Random Forest

### 1. Training Random Forest Model on Training Set

In [41]:
# Building Naive Bayes Model on our dataset
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

### 2. Predicting a Single Result

In [42]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [2 2]
 [3 3]
 [0 0]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [3 3]
 [4 4]
 [4 4]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [4 4]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [3 3]
 [0 0]
 [1 1]
 [4 4]
 [0 0]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [4 4]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [0 0]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [3 3]
 [4 4]
 [1 1]
 [4 4]
 [0 0]
 [3 3]
 [0 0]
 [4 4]
 [4 4]
 [1 1]
 [4 4]
 [4 4]
 [0 0]
 [3 3]
 [1 2]
 [3 3]
 [4 4]
 [4 4]
 [1 1]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [1 1]
 [0 0]
 [3 3]
 [4 4]
 [1 1]
 [0 0]
 [0 0]
 [4 4]
 [0 0]
 [2 2]
 [4 4]
 [3 3]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [3 3]
 [4 4]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [1 1]
 [2 2]
 [4 4]
 [0 0]
 [0 0]
 [4 4]

### 3. Making The Confusion Matrix

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[36  0  0  0  0]
 [ 0 25  0  0  0]
 [ 0  1 29  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 37]]


In [44]:
accuracy_score(y_test,y_pred)

0.9936708860759493

Kesimpulan :
Setelah Data di clean terdapat 8 data duplicate kemudian data duplicate di drom sehingga dari data awal terdiri dari 683 rows x 11 columns, setelah di cleaning menjadi 675 rows x 11 columns.

Dengan mengunakan split data dimana dengan pembagian data test set 25% dan Train set 75% kemudian diuji ke-8 Klasifikasi dan memperoleh nilai sebKagai berikut

1. Logistic Regression (Classification) 
    Akurasi Score = 1.0
2. KNN
    Akurasi Score = 1.0
3. SVM
    Akurasi Score = 1.0
4. Kernel SVM
    Akurasi Score = 1.0
5. Naive Bayes 
    Akurasi Score = 1.0
6. Decision Tree 
    Akurasi Score = 0.9936
7. Random Forest
    Akurasi Score = 0.9936
    
Dari ke-8 Kalsifikasi diatas dapat kita lihat pada Decision Tree dan Random Forest memiliki akurasi score tentinggi yaitu senilai 0.9936 sehingaa dapat disimpilkan dnegan menggunakan data ini lebih tepat untuk melakukan uji menggunakan Random Forest dan Decision Tree
